apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jb1ay58p6-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jb1ay58p6-java-quarkus-gitops